// GET ALL
export const ADMIN_USER_LIST_REQUEST = "ADMIN_USER_LIST_REQUEST";
export const ADMIN_USER_LIST_SUCCESS = "ADMIN_USER_LIST_SUCCESS";
export const ADMIN_USER_LIST_FAIL = "ADMIN_USER_LIST_FAIL";

// CREATE
export const ADMIN_USER_CREATE_REQUEST = "ADMIN_USER_CREATE_REQUEST";
export const ADMIN_USER_CREATE_SUCCESS = "ADMIN_USER_CREATE_SUCCESS";
export const ADMIN_USER_CREATE_FAIL = "ADMIN_USER_CREATE_FAIL";

// UPDATE
export const ADMIN_USER_UPDATE_REQUEST = "ADMIN_USER_UPDATE_REQUEST";
export const ADMIN_USER_UPDATE_SUCCESS = "ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAIL = "ADMIN_USER_UPDATE_FAIL";

// DELETE
export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAIL = "ADMIN_USER_DELETE_FAIL";

//SEARCH
export const ADMIN_USER_SREACH_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_SREACH_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_SREACH_FAIL = "ADMIN_USER_DELETE_FAIL";
