export const ADMIN_GET_REGISTER_REQUEST = "ADMIN_GET_REGISTER_REQUEST";
export const ADMIN_GET_REGISTER_SUCCESS = "ADMIN_GET_REGISTER_SUCCESS";
export const ADMIN_GET_REGISTER_FAIL = "ADMIN_GET_REGISTER_FAIL";
export const ADMIN_DELETE_REGISTER_REQUEST = "ADMIN_DELETE_REGISTER_REQUEST";
export const ADMIN_DELETE_REGISTER_SUCCESS = "ADMIN_DELETE_REGISTER_SUCCESS";
export const ADMIN_DELETE_REGISTER_FAIL = "ADMIN_DELETE_REGISTER_FAIL";
