// BLOG ACTIONS
export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_FAIL = "BLOG_CREATE_FAIL";

export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAIL = "BLOG_UPDATE_FAIL";

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";

export const BLOG_DETAIL_REQUEST = "BLOG_DETAIL_REQUEST";
export const BLOG_DETAIL_SUCCESS = "BLOG_DETAIL_SUCCESS";
export const BLOG_DETAIL_FAIL = "BLOG_DETAIL_FAIL";

export const BLOG_SEARCH_REQUEST = "BLOG_SEARCH_REQUEST";
export const BLOG_SEARCH_SUCCESS = "BLOG_SEARCH_SUCCESS";
export const BLOG_SEARCH_FAIL = "BLOG_SEARCH_FAIL";

// COMMENT ACTIONS
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_FAIL = "COMMENT_CREATE_FAIL";
export const COMMENT_CREATE_OPTIMISTIC = "COMMENT_CREATE_OPTIMISTIC";
export const COMMENT_CREATE_ROLLBACK = "COMMENT_CREATE_ROLLBACK";

export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAIL = "COMMENT_UPDATE_FAIL";
export const COMMENT_UPDATE_OPTIMISTIC = "COMMENT_UPDATE_OPTIMISTIC";
export const COMMENT_UPDATE_ROLLBACK = "COMMENT_UPDATE_ROLLBACK";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";
export const COMMENT_DELETE_OPTIMISTIC = "COMMENT_DELETE_OPTIMISTIC";
export const COMMENT_DELETE_ROLLBACK = "COMMENT_DELETE_ROLLBACK";

// REACTION ACTIONS
export const REACTION_DROP_REQUEST = "REACTION_DROP_REQUEST";
export const REACTION_DROP_SUCCESS = "REACTION_DROP_SUCCESS";
export const REACTION_DROP_FAIL = "REACTION_DROP_FAIL";

export const REACTION_STATS_REQUEST = "REACTION_STATS_REQUEST";
export const REACTION_STATS_SUCCESS = "REACTION_STATS_SUCCESS";
export const REACTION_STATS_FAIL = "REACTION_STATS_FAIL";

export const REACTION_MY_REQUEST = "REACTION_MY_REQUEST";
export const REACTION_MY_SUCCESS = "REACTION_MY_SUCCESS";
export const REACTION_MY_FAIL = "REACTION_MY_FAIL";

// UI ACTIONS
export const SET_CURRENT_BLOG = "SET_CURRENT_BLOG";
export const CLEAR_CURRENT_BLOG = "CLEAR_CURRENT_BLOG";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
export const PREVENT_REFRESH = "PREVENT_REFRESH";
