export const USER_GET_LIST_CLASS_REQUEST = "USER_GET_LIST_CLASS_REQUESTT";
export const USER_GET_LIST_CLASS_SUCCESS = "USER_GET_LIST_CLASS_SUCCESS";
export const USER_GET_LIST_CLASS_FAIL = "USER_GET_LIST_CLASS_FAIL";
export const USER_DELETE_CLASS_REQUEST = "USER_DELETE_CLASS_REQUEST";
export const USER_DELETE_CLASS_SUCCESS = "USER_DELETE_CLASS_SUCCESS";
export const USER_DELETE_CLASS_FAIL = "USER_DELETE_CLASS_FAIL";
